<a href="https://colab.research.google.com/github/linhtoroi/hihi/blob/main/DS_TEST_PRACTICE_T6_2022.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## ĐÁNH GIÁ NĂNG LỰC KỸ SƯ KHOA HỌC DỮ LIỆU THÁNG 06 - 2022
#### BÀI THỰC HÀNH (ĐỀ CHÍNH THỨC)

---

Ngày test: 27/06/2022
Thời gian làm bài: 40 phút, từ 17:00 đến 17:40
(+ 5 phút thiết lập môi trường và nộp bài)


**Quy định:**
- Không trao đổi trong suốt quá trình làm bài
- Record màn hình làm bài và share lại cho quanvh8 sau khi kết thúc thời gian test
- **ĐƯỢC** sử dụng tài liệu và tra cứu internet
- Sau khi hoàn thành, tải notebook, gửi về email: quanvh8@viettel.com.vn

**Hướng dẫn làm bài:**

* Chạy toàn bộ lệnh trong phần 0. CHUẨN BỊ MÔI TRƯỜNG
* Làm theo hướng dẫn tại các câu và **CHỈ SỬA** các đoạn code nằm giữa các thẻ:

      # YOUR CODE START
      # / END YOUR CODE

*Lưu ý: hầu hết câu hỏi không có tính tuần tự (không cần hoàn thành câu trước để làm câu sau)*

*Đề thi có một số testcase hỗ trợ DS kiểm tra kết quả, nhưng đây không phải điểm số. Điểm số được giám khảo chấm và gửi lại sau.*



---

### 0. CÀI ĐẶT MÔI TRƯỜNG
Guide: Chạy toàn bộ các lệnh trong phần này

In [ ]:
!pip install pyspark

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 281.4/281.4 MB 4.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.7/199.7 KB 20.2 MB/s eta 0:00:00
  Created wheel for pyspark: filename=pyspark-3.3.2-py2.py3-none-any.whl size=281824028 sha256=4179865b6a8c66518e7fccf46ac1c16f16d29604897e8b06b3a4fd482f45d384
  Stored in directory: /root/.cache/pip/wheels/6c/e3/9b/0525ce8a69478916513509d43693511463c6468db0de237c86
Successfully built pyspark
  Attempting uninstall: py4j
    Found existing installation: py4j 0.10.9.7
    Uninstalling py4j-0.10.9.7:
      Successfully uninstalled py4j-0.10.9.7


In [ ]:
import pandas as pd
import numpy as np 
import tensorflow as tf
import gzip
import shutil
import requests 
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import roc_auc_score

import pyspark
from pyspark.sql import functions as F

In [ ]:
def data_downloader(file_name):
    file_url = 'https://web.archive.org/web/20070214120527/http://lisp.vse.cz/pkdd99/DATA/'+file_name
    file_path = "/content/"+file_name
    
    r = requests.get(file_url, stream = True, verify=False) 
    
    with open( file_path, "wb") as file: 
        for block in r.iter_content(chunk_size = 1024*10): 
            if block: 
                file.write(block)
    print("Loaded "+file_name+" to local path: "+file_path)
    

In [ ]:
spark = pyspark.sql.SparkSession \
    .builder \
    .appName("DS_test") \
    .getOrCreate()

#### DATA: PKDD'99 Financial dataset

Thông tin bộ dữ liệu: https://relational.fit.cvut.cz/dataset/Financial

PKDD'99 Financial dataset contains 606 successful and 76 not successful loans along with their information and transactions.

![Alt text](https://relational.fit.cvut.cz/assets/img/datasets-generated/financial.svg "Schema bộ dữ liệu")

In [ ]:
# Tải dữ liệu về
data_downloader("data_berka.zip")

/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'web.archive.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(


Loaded data_berka.zip to local path: /content/data_berka.zip


In [ ]:
!unzip /content/data_berka.zip

Archive:  /content/data_berka.zip
  inflating: trans.asc               
  inflating: order.asc               
  inflating: loan.asc                
  inflating: district.asc            
  inflating: disp.asc                
  inflating: client.asc              
  inflating: card.asc                
  inflating: account.asc             


Dữ liệu đã được tải về colab, mở tab "Files" bên trái màn hình để kiếm tra

In [ ]:
# Setting to speed up 
spark.sql("set spark.sql.shuffle.partitions=1")

DataFrame[key: string, value: string]

## PHẦN I. PYTHON PROGRAMMING
[4 điểm]
Guide: Sử dụng python thực hiện các yêu cầu sau

**Câu 1**. [2đ] Cho $A$ là một chuỗi thời gian (kiểu dữ liệu numpy array hoặc list), xây dựng thuật toán tìm ra chuỗi con $a \in A$ sao cho $S = a[-1] - a[0]$ (hiệu số phần tử cuối cùng và phần tử đầu tiên) là tối đa và độ phức tạp của thuật toán là $O(n)$


In [ ]:
%%time
def get_subseq(A):
  # YOUR CODE START 

  a = 
  # / END YOUR CODE
  return a

In [ ]:
# Testcase
A= [1, 2, 5, 0.5,4, 6, 8, 12, 10, 15, 9, 7, 6, 5, 4, 7, 8 ,9 ]
a = get_subseq(A)
print(a)

# >> expected result: [0.5, 4, 6, 8, 12, 10, 15]

**Câu 2**. [2đ] Vẫn thực hiện yêu cầu của Câu 1 với điều kiện độ dài tối đa của chuỗi $a$ là $k$

In [ ]:
%%time
def get_subseq_limit(A, k):
  # YOUR CODE START 

  a = 
  # / END YOUR CODE
  return a

In [ ]:
# Testcase
A= [1, 2, 5, 0.5,4, 6, 8, 12, 10, 15, 9, 7, 6, 5, 4, 7, 8 ,9 ]
a = get_subseq_limit(A, k=3)
print(a)

# >> expected result: [6, 8, 12]

## PHẦN II. DATA MANIPULATION AND ANALYSIS
[ 10 điểm ] <br>
Guide: Sử dụng pyspark hoặc spark-SQL thực hiện tất cả các câu thuộc phần này.

**Câu 3**. [2đ] Đọc các file vào pyspark dataframe, biết rằng các cột trong các file dữ liệu đều phân cách nhau bởi dấu chấm phấy (;). Lưu tương ứng các dataframe với các file dữ liệu:
- df_loan : "loan.asc"
- df_trans  :"trans.asc"
- df_order  :"order.asc"
- df_account  :"account.asc"

(Xem mô tả quan trọng của dữ liệu phía trên)

In [ ]:
df_loan =  spark.read.options(header = 'True', inferSchema = 'True', delimiter=';').csv('/content/loan.asc')
df_trans = spark.read.options(header = 'True', inferSchema = 'True', delimiter=';').csv('/content/trans.asc') 
df_order = spark.read.options(header = 'True', inferSchema = 'True', delimiter=';').csv('/content/order.asc')
df_account = spark.read.options(header = 'True', inferSchema = 'True', delimiter=';').csv('/content/account.asc')

In [ ]:
df_loan.show(5)

+-------+----------+------+------+--------+--------+------+
|loan_id|account_id|  date|amount|duration|payments|status|
+-------+----------+------+------+--------+--------+------+
|   5314|      1787|930705| 96396|      12|  8033.0|     B|
|   5316|      1801|930711|165960|      36|  4610.0|     A|
|   6863|      9188|930728|127080|      60|  2118.0|     A|
|   5325|      1843|930803|105804|      36|  2939.0|     A|
|   7240|     11013|930906|274740|      60|  4579.0|     A|
+-------+----------+------+------+--------+--------+------+
only showing top 5 rows



**Câu 4**. [2đ] Truy xuất top 10 quận (district_id) có số lượng account_id phát hành hàng tháng (tương ứng frequency là POPLATEK MESICNE) là lớn nhất

In [ ]:
df_account.show(5)

+----------+-----------+----------------+------+
|account_id|district_id|       frequency|  date|
+----------+-----------+----------------+------+
|       576|         55|POPLATEK MESICNE|930101|
|      3818|         74|POPLATEK MESICNE|930101|
|       704|         55|POPLATEK MESICNE|930101|
|      2378|         16|POPLATEK MESICNE|930101|
|      2632|         24|POPLATEK MESICNE|930102|
+----------+-----------+----------------+------+
only showing top 5 rows



In [ ]:
t

In [ ]:
%%time
# YOUR CODE START 
df_account.filter(F.col('frequency')=='POPLATEK MESICNE')\
.groupby('district_id').agg(F.count('account_id').alias('cnt')).sort(F.col('cnt').desc()).limit(10).show()

# / END YOUR CODE

+-----------+---+
|district_id|cnt|
+-----------+---+
|          1|509|
|         70|145|
|         74|124|
|         54|121|
|         72| 81|
|         68| 81|
|         64| 81|
|          5| 60|
|         46| 56|
|         59| 55|
+-----------+---+

CPU times: user 11.8 ms, sys: 530 µs, total: 12.3 ms
Wall time: 559 ms


**Câu 5**. [3đ]
Xây dựng ma trận tỷ lệ % loại nợ là A (df_loan.status) tương ứng với loại tài khoản (df_account.frequency) và thời hạn khoản vay (df_loan.duration).

Yêu cầu ma trận: cột: loại tài khoản frequency, hàng: thời hạn khoản vay duration, giá trị: tỷ lệ số lượng nợ A/ tổng số lượng khoản nợ

In [ ]:
df_loan.show(10)

+-------+----------+------+------+--------+--------+------+
|loan_id|account_id|  date|amount|duration|payments|status|
+-------+----------+------+------+--------+--------+------+
|   5314|      1787|930705| 96396|      12|  8033.0|     B|
|   5316|      1801|930711|165960|      36|  4610.0|     A|
|   6863|      9188|930728|127080|      60|  2118.0|     A|
|   5325|      1843|930803|105804|      36|  2939.0|     A|
|   7240|     11013|930906|274740|      60|  4579.0|     A|
|   6687|      8261|930913| 87840|      24|  3660.0|     A|
|   7284|     11265|930915| 52788|      12|  4399.0|     A|
|   6111|      5428|930924|174744|      24|  7281.0|     B|
|   7235|     10973|931013|154416|      48|  3217.0|     A|
|   5997|      4894|931104|117024|      24|  4876.0|     A|
+-------+----------+------+------+--------+--------+------+
only showing top 10 rows



In [ ]:
df_account.show(10)

+----------+-----------+------------------+------+
|account_id|district_id|         frequency|  date|
+----------+-----------+------------------+------+
|       576|         55|  POPLATEK MESICNE|930101|
|      3818|         74|  POPLATEK MESICNE|930101|
|       704|         55|  POPLATEK MESICNE|930101|
|      2378|         16|  POPLATEK MESICNE|930101|
|      2632|         24|  POPLATEK MESICNE|930102|
|      1972|         77|  POPLATEK MESICNE|930102|
|      1539|          1|POPLATEK PO OBRATU|930103|
|       793|         47|  POPLATEK MESICNE|930103|
|      2484|         74|  POPLATEK MESICNE|930103|
|      1695|         76|  POPLATEK MESICNE|930103|
+----------+-----------+------------------+------+
only showing top 10 rows



In [ ]:
%%time
# YOUR CODE START 

df_loan.withColumn('status_1',F.when(F.col('status')=='A', 1).otherwise(0)).join(df_account, on="account_id").groupby('frequency').pivot('duration')\
.agg(F.sum('status_1')/F.count('status_1')).show()
# / END YOUR CODE

+------------------+------------------+------------------+-------------------+-------------------+--------------------+
|         frequency|                12|                24|                 36|                 48|                  60|
+------------------+------------------+------------------+-------------------+-------------------+--------------------+
|  POPLATEK MESICNE|0.7142857142857143|0.4824561403508772|0.22448979591836735|0.07894736842105263| 0.01652892561983471|
|    POPLATEK TYDNE|0.7857142857142857|               0.4|               0.28|              0.125|0.047619047619047616|
|POPLATEK PO OBRATU|               0.4|0.3333333333333333|0.42857142857142855|                0.0|                 0.0|
+------------------+------------------+------------------+-------------------+-------------------+--------------------+

CPU times: user 15.2 ms, sys: 0 ns, total: 15.2 ms
Wall time: 1.01 s


**Câu 6**. [3đ] Ngân hàng quen thuộc của một account_id được định nghĩa là ngân hàng (df_order.bank_to) mà có tổng số giá trị giao dịch (df_order.amount) mà người account_id đó giao dịch nhiều nhất. Trong số các account_id phát hành hàng tháng (POPLATEK MESICNE), người dùng của ngân hàng quen thuộc nào có tỷ lệ nợ loại A thấp nhất?

In [ ]:
%%time
# YOUR CODE START 
df_order.show(5)


# / END YOUR CODE

+--------+----------+-------+----------+------+--------+
|order_id|account_id|bank_to|account_to|amount|k_symbol|
+--------+----------+-------+----------+------+--------+
|   29401|         1|     YZ|  87144583|2452.0|    SIPO|
|   29402|         2|     ST|  89597016|3372.7|    UVER|
|   29403|         2|     QR|  13943797|7266.0|    SIPO|
|   29404|         3|     WX|  83084338|1135.0|    SIPO|
|   29405|         3|     CD|  24485939| 327.0|        |
+--------+----------+-------+----------+------+--------+
only showing top 5 rows

CPU times: user 2.78 ms, sys: 1.03 ms, total: 3.8 ms
Wall time: 188 ms


In [ ]:
df_account.join(df_order, on="account_id", how="left").join(df_loan, on="account_id").withColumn('A', F.when(F.col('status')=='A', 1).otherwise(0))\
.groupby('bank_to').agg((F.sum('A')/F.count('A')).alias('ratio')).orderBy('ratio').show(1)

+-------+------------------+
|bank_to|             ratio|
+-------+------------------+
|     WX|0.2644628099173554|
+-------+------------------+
only showing top 1 row



### PHẦN III. MODELING
TỰ CHỌN <br>
[ 6 điểm ] <br>
DS chọn 1 trong 2 câu II.a hoặc II.b
**Chỉ sử dụng dữ liệu train đã được chia sẵn để huấn luyện model, không sử dụng tập test.** <br>
Có thể sử dụng tập test để đánh giá độ chính xác của model.

Điểm số được chấm dựa trên độ chính xác của model trên tập test.

**Yêu cầu**: xây dựng mô hình học máy phân loại loại nợ (df_loan.status) dựa trên thông tin từ các bảng dữ liệu đã có (trừ trường nhãn df_loan.status, được sử dụng tất cả các trường còn lại)

**Câu III.a**. Xây dựng mô hình trên môi trường pyspark

In [ ]:
# CHẠY ĐOẠN CODE SAU|
train_label, test_label = df_loan.randomSplit([0.7, 0.3], seed=12345)

Chỉ sử dụng các loan_id trong tập train và huấn luyện model

**YÊU CẦU ĐẦU RA** <br>
Dataframe: df_pred {loan_id: int, status: varchar}, trong đó loan_id là các id tương ứng trong bộ test_label

In [ ]:
df_pred = test_label[['loan_id', 'status']]

In [ ]:
train_label.join(df_account, on='account_id', how='left').join(df_order, on='account_id', how='left').show(5)

+----------+-------+------+------+--------+--------+------+-----------+----------------+------+--------+-------+----------+------+--------+
|account_id|loan_id|  date|amount|duration|payments|status|district_id|       frequency|  date|order_id|bank_to|account_to|amount|k_symbol|
+----------+-------+------+------+--------+--------+------+-----------+----------------+------+--------+-------+----------+------+--------+
|         2|   4959|940105| 80952|      24|  3373.0|     A|          1|POPLATEK MESICNE|930226|   29403|     QR|  13943797|7266.0|    SIPO|
|         2|   4959|940105| 80952|      24|  3373.0|     A|          1|POPLATEK MESICNE|930226|   29402|     ST|  89597016|3372.7|    UVER|
|        19|   4961|960429| 30276|      12|  2523.0|     B|         21|POPLATEK MESICNE|950407|   29423|     QR|  14132368|2523.2|    UVER|
|        25|   4962|971208| 30276|      12|  2523.0|     A|         68|POPLATEK MESICNE|960728|   29434|     WX|  52864879| 164.0|POJISTNE|
|        25|   4962|

**Câu III.b**. Xây dựng mô hình với pandas (sklearn hoặc tensorflow)

In [ ]:
# CHẠY ĐOẠN CODE SAU
train_label, test_label = df_loan.randomSplit([0.7, 0.3], seed=12345)
train_label = train_label.toPandas()
test_label = test_label.toPandas()

In [ ]:
train_label.merge(df_account.toPandas(), on='account_id', how='left').head(5)

loan_id  account_id  date_x  amount  duration  payments status  \
0     4959           2  940105   80952        24    3373.0      A   
1     4961          19  960429   30276        12    2523.0      B   
2     4962          25  971208   30276        12    2523.0      A   
3     4967          37  981014  318480        60    5308.0      D   
4     4968          38  980419  110736        48    2307.0      C   

   district_id         frequency  date_y  
0            1  POPLATEK MESICNE  930226  
1           21  POPLATEK MESICNE  950407  
2           68  POPLATEK MESICNE  960728  
3           20  POPLATEK MESICNE  970818  
4           19    POPLATEK TYDNE  970808

Chỉ sử dụng các loan_id trong tập train và huấn luyện model

**YÊU CẦU ĐẦU RA** <br>
Dataframe: df_pred {loan_id: int, status: varchar}, trong đó loan_id là các id tương ứng trong bộ test_label

In [ ]:
# YOUR CODE START 
train_data = train_label.merge(df_account.toPandas(), on='account_id', how='left').merge(df_order.toPandas(), on='account_id', how='left')
test_data = test_label.merge(df_account.toPandas(), on='account_id', how='left').merge(df_order.toPandas(), on='account_id', how='left')


# / END YOUR CODE

In [ ]:
drop_col = ['loan_id', 'account_id', 'date_x', 'date_y', 'order_id', 'account_to']


In [ ]:
from sklearn import preprocessing
from collections import defaultdict
d = defaultdict(preprocessing.LabelEncoder)
train_data_processing = train_data[[k for k, v in train_data.dtypes.to_dict().items() if k not in drop_col and v=='O']].apply(lambda x: d[x.name].fit_transform(x))
train_data_processing = pd.concat([train_data_processing, train_data[[k for k, v in train_data.dtypes.to_dict().items() if k not in drop_col and v!='O']]], axis=1)

test_data_processing = test_data[[k for k, v in test_data.dtypes.to_dict().items() if k not in drop_col and v=='O']].apply(lambda x: d[x.name].transform(x))
test_data_processing = pd.concat([test_data_processing, test_data[[k for k, v in test_data.dtypes.to_dict().items() if k not in drop_col and v!='O']]], axis=1)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
clf = RandomForestClassifier(max_depth=10, random_state=0)
clf.fit(train_data_processing.drop('status', axis=1), train_data_processing['status'])

RandomForestClassifier(max_depth=10, random_state=0)

In [ ]:
from sklearn.metrics import confusion_matrix, f1_score

y_pred = clf.predict(test_data_processing.drop('status', axis=1))

print(confusion_matrix(test_data_processing['status'], y_pred))
print(f1_score(test_data_processing['status'], y_pred, average="micro"))

[[ 60   1  50   2]
 [ 12   0  12   0]
 [ 49   0 190   3]
 [  1   0  22   0]]
0.6218905472636815


In [ ]:
from sklearn.svm import SVC
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
clf = make_pipeline(StandardScaler(), SVC(gamma='auto'))

clf.fit(train_data_processing.drop('status', axis=1), train_data_processing['status'])

from sklearn.metrics import confusion_matrix, f1_score

y_pred = clf.predict(test_data_processing.drop('status', axis=1))

print(confusion_matrix(test_data_processing['status'], y_pred))
print(f1_score(test_data_processing['status'], y_pred, average="micro"))


[[ 70   0  43   0]
 [ 15   0   9   0]
 [ 47   0 195   0]
 [  1   0  22   0]]
0.6592039800995025


In [ ]:
!pip install catboost

In [ ]:
from catboost import CatBoostClassifier

model = CatBoostClassifier(iterations=2, depth=1, learning_rate=0.1)
model.fit(train_data_processing.drop('status', axis=1),
          train_data_processing['status'],
          verbose=False)

from sklearn.metrics import confusion_matrix, f1_score

y_pred = model.predict(test_data_processing.drop('status', axis=1))

print(confusion_matrix(test_data_processing['status'], y_pred))
print(f1_score(test_data_processing['status'], y_pred, average="micro"))


[[ 78   0  35   0]
 [ 15   0   9   0]
 [ 44   0 198   0]
 [  1   0  22   0]]
0.6865671641791045


In [ ]:
confusion_matrix(test_data_processing['status'], y_pred)

array([[ 78,   0,  35,   0],
       [ 15,   0,   9,   0],
       [ 44,   0, 198,   0],
       [  1,   0,  22,   0]])

--- YOUR TEST END HERE ---